"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Facepalm.py']
APP_NAME = 'Facepalm 🤦🏻‍♂️'
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'spock.icns'
    'plist': {
    	'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Rock Paper Scissors Lizard Spock",
        'CFBundleIdentifier': "com.metachris.osx.facepalm",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2017, Marta Zaryn, All Rights Reserved😄",
    }
}

setup(
	name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

